on:
  workflow_dispatch:
    inputs:
      app_version:
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: ">=20.15.1"
          architecture: "x64"
      - run: |
          npm i
          cd native
          npm i
          npm run build
          cd ..
          npm run app:build
      - uses: actions/upload-artifact@v4
        with:
          path: |
            release/${{ inputs.app_version }}/autoclicker_${{ inputs.app_version }}.exe
            release/${{ inputs.app_version }}/autoclicker_${{ inputs.app_version }}.7z